[PERF] - Use native client size
svgdotjs/svg.panzoom.js pull request #36
Opened 2019-01-05 09:17 UTC by ltouati

Use clientWidth & clientHeight that seem to give much better performance on chrome when moving very large graphs

2019-01-05 09:57 UTC, Fuzzyma requested changes
Awesome catch!
I always disliked the current solution and totally forgot about clientHeight.
Get rid of the semicolon and we are ready to merge :)

2019-01-05 09:57 UTC, Fuzzyma commented on src/svg.panzoom.js
> +      , zoom = Math.min(zoomX, zoomY);
We dont do semicolons here ;)

2019-01-05 10:25 UTC, ltouati commented
Hi @Fuzzyma 
Thanks for the feedback, just updated the file

L.

2019-01-05 10:28 UTC, Fuzzyma approved these changes

2019-01-05 10:28 UTC, merged

2019-01-18 18:07 UTC, Fuzzyma commented
@ltouati I just realized, that clientHeight is not working in FF for svg elements.
Thats obviously bad because it has to work in all browsers. I think I need to revert this PR :/

2019-01-18 18:10 UTC, Fuzzyma commented
Bugreport for this: https://bugzilla.mozilla.org/show_bug.cgi?id=874811